python src/main.py \
    --dataset 'idmeme'\
    --num_mapping_layers 1 \
    --map_dim 768 \
    --fusion align \
    --num_pre_output_layers 3 \
    --drop_probs 0.4 0.5 0.3 \
    --gpus '0' \
    --batch_size 16 \
    --lr 0.000013 \
    --max_epochs 10 \
    --name 'text-inv-comb' \
    --pretrained_model '' \
    --reproduce f \
    --pretrained_proj_weights f \
    --freeze_proj_layers f \
    --comb_proj t \
    --comb_fusion align \
    --convex_tensor f \
    --phi_inv_proj t \
    --text_inv_proj t \
    --post_inv_proj t \
    --enh_text t \
    --phi_freeze f \
    --fast_process t \
    --clip_model 'm-CLIP' \
    --use_smote \
    --smote_strategy 'auto'